export default [
  { label: '  Acupuntura', value: '  Acupuntura' },
  { label: 'Alergia e Imunologia', value: 'Alergia e Imunologia' },
  { label: 'Anestesiologia', value: 'Anestesiologia' },
  { label: 'Angiologia', value: 'Angiologia' },
  { label: 'Cardiologia', value: 'Cardiologia' },
  { label: 'Cirurgia Cardiovascular', value: 'Cirurgia Cardiovascular' },
  { label: 'Cirurgia da Mão', value: 'Cirurgia da Mão' },
  {
    label: 'Cirurgia de Cabeça e Pescoço',
    value: 'Cirurgia de Cabeça e Pescoço',
  },
  {
    label: 'Cirurgia do Aparelho Digestivo',
    value: 'Cirurgia do Aparelho Digestivo',
  },
  { label: 'Cirurgia Geral', value: 'Cirurgia Geral' },
  { label: 'Cirurgia Oncológica', value: 'Cirurgia Oncológica' },
  { label: 'Cirurgia Pediátrica', value: 'Cirurgia Pediátrica' },
  { label: 'Cirurgia Plástica', value: 'Cirurgia Plástica' },
  { label: 'Cirurgia Torácica', value: 'Cirurgia Torácica' },
  { label: 'Cirurgia Vascular', value: 'Cirurgia Vascular' },
  { label: 'Clínica Médica', value: 'Clínica Médica' },
  { label: 'Coloproctologia', value: 'Coloproctologia' },
  { label: 'Dermatologia', value: 'Dermatologia' },
  {
    label: 'Endocrinologia e Metabologia',
    value: 'Endocrinologia e Metabologia',
  },
  { label: 'Endoscopia', value: 'Endoscopia' },
  { label: 'Gastroenterologia', value: 'Gastroenterologia' },
  { label: 'Genética Médica', value: 'Genética Médica' },
  { label: 'Geriatria', value: 'Geriatria' },
  { label: 'Ginecologia e Obstetrícia', value: 'Ginecologia e Obstetrícia' },
  { label: 'Hematologia e Hemoterapia', value: 'Hematologia e Hemoterapia' },
  { label: 'Homeopatia', value: 'Homeopatia' },
  { label: 'Infectologia', value: 'Infectologia' },
  { label: 'Mastologia', value: 'Mastologia' },
  { label: 'Medicina de Emergência', value: 'Medicina de Emergência' },
  {
    label: 'Medicina de Família e Comunidade',
    value: 'Medicina de Família e Comunidade',
  },
  { label: 'Medicina do Trabalho', value: 'Medicina do Trabalho' },
  { label: 'Medicina de Tráfego', value: 'Medicina de Tráfego' },
  { label: 'Medicina Esportiva', value: 'Medicina Esportiva' },
  {
    label: 'Medicina Física e Reabilitação',
    value: 'Medicina Física e Reabilitação',
  },
  { label: 'Medicina Intensiva', value: 'Medicina Intensiva' },
  {
    label: 'Medicina Legal e Perícia Médica',
    value: 'Medicina Legal e Perícia Médica',
  },
  { label: 'Medicina Nuclear', value: 'Medicina Nuclear' },
  {
    label: 'Medicina Preventiva e Social',
    value: 'Medicina Preventiva e Social',
  },
  { label: 'Nefrologia', value: 'Nefrologia' },
  { label: 'Neurocirurgia', value: 'Neurocirurgia' },
  { label: 'Neurologia', value: 'Neurologia' },
  { label: 'Nutrologia', value: 'Nutrologia' },
  { label: 'Oftalmologia', value: 'Oftalmologia' },
  { label: 'Oncologia Clínica', value: 'Oncologia Clínica' },
  { label: 'Ortopedia e Traumatologia', value: 'Ortopedia e Traumatologia' },
  { label: 'Otorrinolaringologia', value: 'Otorrinolaringologia' },
  { label: 'Patologia', value: 'Patologia' },
  {
    label: 'Patologia Clínica/ Medicina Laboratorial',
    value: 'Patologia Clínica/ Medicina Laboratorial',
  },
  { label: 'Pediatria', value: 'Pediatria' },
  { label: 'Pneumologia', value: 'Pneumologia' },
  { label: 'Psiquiatria', value: 'Psiquiatria' },
  {
    label: 'Radiologia e Diagnóstico por Imagem',
    value: 'Radiologia e Diagnóstico por Imagem',
  },
  { label: 'Radioterapia', value: 'Radioterapia' },
  { label: 'Reumatologia', value: 'Reumatologia' },
];
